### ISSUE TITLE
Ionic v4 and Google maps Native

### ISSUE THREAD

**Issue by wuilmerj24** [ionic-team/ionic-native-google-maps#53]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

Is it compatible with the ionic v4?

**Comment by wf9a5m75** [comment]
I think ionic v4 is not released officially yet.

**Comment by wuilmerj24** [comment]
I install it but events do not trigger them. Only the map_ready

**Comment by wf9a5m75** [comment]
Yes, `status: working` does not mean `complete`. I'm still working on.

**Comment by wf9a5m75** [comment]
Ok, I created `@ionic-native/google-maps@5.0.14-beta`.
https://www.npmjs.com/package/@ionic-native/google-maps/v/5.0.0-beta.14

Please reinstall with `@ionic-native/google-maps@5.0.14-beta` with `cordova-plugin-googlemaps@2.3.9`.

I confirmed both works on Android (sorry, iOS is not yet well).

**Comment by wuilmerj24** [comment]
@wf9a5m75 hi.
Ok. 
Thanks man

**Comment by frandisag** [comment]
Still get an error when building gradle, please help me guys.

Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> A problem occurred starting process 'command 'C:\Users\SPV IT 2\AppData\Local\Android\Sdk\ndk-bundle\toolchains\mips64el-linux-android-4.9\prebuilt\windows-x86_64\bin\mips64el-linux-android-strip''

thanks

**Comment by wuilmerj24** [comment]
Hello @wf9a5m75 
Could you upload an example?
I could not load the map.

**Comment by wf9a5m75** [comment]
This is not perfect example, but you can try this.
https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4

**Comment by wf9a5m75** [comment]
@frandisag Don't jump in to unrelated issue thread, please.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/mips64el-linux-android-strip/README.md

**Comment by wf9a5m75** [comment]
@wuilmerj24  Please install the plugin from multiple_maps branch.

**Comment by wuilmerj24** [comment]
@wf9a5m75 okay thanks

**Comment by frandisag** [comment]
@wf9a5m75 sorry for that, i just tried ionic v4 and google maps native and found that error.
failed when build gradle for android studio using ndx 17.xxx.
i has figured out to solve this problem for android studio, just downgrade your version to ndx 16.xx stable version if you found this problem.
thanks guys

**Comment by wf9a5m75** [comment]
**update**

I just released `@ionic-native/google-maps@5.0.0-beta.15`. 
https://www.npmjs.com/package/@ionic-native/google-maps/v/5.0.0-beta.15

You need to use it with the `multiple_maps` branch.
```
$> ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."

$> npm install @ionic-native/core@5.0.0-beta.14 @ionic-native/google-maps@5.0.0-beta.15 --save
```

## demo
https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4

**Comment by bpadovese** [comment]
Trying to install this latest version `@ionic-native/google-maps@5.0.0-beta.15` results in the following error:

No matching version found for @ionic-native/google-maps@5.0.0-beta.15

`@ionic-native/google-maps@5.0.0-beta.14` works though.

**Comment by wf9a5m75** [comment]
Yes, I removed it at once.

**Comment by surfersat** [comment]
Hi!
I tested few examples with this plugin but it still showing blank map, in browser and phone debug.
What can i check to show the map properly?

Thank you!

**Comment by wf9a5m75** [comment]
`browser` is not supported.

**Comment by wf9a5m75** [comment]
`@ionic-native/google-maps@5.0.0-beta.16` is available now.
(But if you use `@ionic-native/google-maps@5.0.0-beta.14`, and there is no problem for you, then you don't need to upgrade)
